/* tslint:disable */
/* eslint-disable */
/**
 * Volunteer Victoria - Community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface OpportunityCreateDto
 */
export interface OpportunityCreateDto {
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  contactName: string;
  /**
   *
   * @type {number}
   * @memberof OpportunityCreateDto
   */
  requiredPeopleCount: number;
  /**
   *
   * @type {number}
   * @memberof OpportunityCreateDto
   */
  startTime: number;
  /**
   *
   * @type {number}
   * @memberof OpportunityCreateDto
   */
  endTime: number;
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  locationName: string;
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  indoorsOrOutdoors: OpportunityCreateDtoIndoorsOrOutdoorsEnum;
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  contactEmail: string | null;
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  contactPhone: string | null;
  /**
   *
   * @type {boolean}
   * @memberof OpportunityCreateDto
   */
  criminalRecordCheckRequired: boolean;
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  idealVolunteer: string | null;
  /**
   *
   * @type {string}
   * @memberof OpportunityCreateDto
   */
  additionalInformation: string | null;
}

/**
 * @export
 */
export const OpportunityCreateDtoIndoorsOrOutdoorsEnum = {
  Indoors: "indoors",
  Outdoors: "outdoors",
} as const;
export type OpportunityCreateDtoIndoorsOrOutdoorsEnum =
  typeof OpportunityCreateDtoIndoorsOrOutdoorsEnum[keyof typeof OpportunityCreateDtoIndoorsOrOutdoorsEnum];

/**
 * Check if a given object implements the OpportunityCreateDto interface.
 */
export function instanceOfOpportunityCreateDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "title" in value;
  isInstance = isInstance && "contactName" in value;
  isInstance = isInstance && "requiredPeopleCount" in value;
  isInstance = isInstance && "startTime" in value;
  isInstance = isInstance && "endTime" in value;
  isInstance = isInstance && "description" in value;
  isInstance = isInstance && "locationName" in value;
  isInstance = isInstance && "indoorsOrOutdoors" in value;
  isInstance = isInstance && "contactEmail" in value;
  isInstance = isInstance && "contactPhone" in value;
  isInstance = isInstance && "criminalRecordCheckRequired" in value;
  isInstance = isInstance && "idealVolunteer" in value;
  isInstance = isInstance && "additionalInformation" in value;

  return isInstance;
}

export function OpportunityCreateDtoFromJSON(json: any): OpportunityCreateDto {
  return OpportunityCreateDtoFromJSONTyped(json, false);
}

export function OpportunityCreateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OpportunityCreateDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: json["title"],
    contactName: json["contactName"],
    requiredPeopleCount: json["requiredPeopleCount"],
    startTime: json["startTime"],
    endTime: json["endTime"],
    description: json["description"],
    locationName: json["locationName"],
    indoorsOrOutdoors: json["indoorsOrOutdoors"],
    contactEmail: json["contactEmail"],
    contactPhone: json["contactPhone"],
    criminalRecordCheckRequired: json["criminalRecordCheckRequired"],
    idealVolunteer: json["idealVolunteer"],
    additionalInformation: json["additionalInformation"],
  };
}

export function OpportunityCreateDtoToJSON(
  value?: OpportunityCreateDto | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    contactName: value.contactName,
    requiredPeopleCount: value.requiredPeopleCount,
    startTime: value.startTime,
    endTime: value.endTime,
    description: value.description,
    locationName: value.locationName,
    indoorsOrOutdoors: value.indoorsOrOutdoors,
    contactEmail: value.contactEmail,
    contactPhone: value.contactPhone,
    criminalRecordCheckRequired: value.criminalRecordCheckRequired,
    idealVolunteer: value.idealVolunteer,
    additionalInformation: value.additionalInformation,
  };
}
