/* tslint:disable */
/* eslint-disable */
/**
 * Volunteer Victoria - Community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface OpportunitySummaryResponseDto
 */
export interface OpportunitySummaryResponseDto {
  /**
   *
   * @type {string}
   * @memberof OpportunitySummaryResponseDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof OpportunitySummaryResponseDto
   */
  contactName: string;
  /**
   *
   * @type {number}
   * @memberof OpportunitySummaryResponseDto
   */
  requiredPeopleCount: number;
  /**
   *
   * @type {number}
   * @memberof OpportunitySummaryResponseDto
   */
  startTime: number;
  /**
   *
   * @type {number}
   * @memberof OpportunitySummaryResponseDto
   */
  endTime: number;
  /**
   *
   * @type {string}
   * @memberof OpportunitySummaryResponseDto
   */
  opportunityId: string;
  /**
   *
   * @type {number}
   * @memberof OpportunitySummaryResponseDto
   */
  postedTime: number;
}

/**
 * Check if a given object implements the OpportunitySummaryResponseDto interface.
 */
export function instanceOfOpportunitySummaryResponseDto(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && "title" in value;
  isInstance = isInstance && "contactName" in value;
  isInstance = isInstance && "requiredPeopleCount" in value;
  isInstance = isInstance && "startTime" in value;
  isInstance = isInstance && "endTime" in value;
  isInstance = isInstance && "opportunityId" in value;
  isInstance = isInstance && "postedTime" in value;

  return isInstance;
}

export function OpportunitySummaryResponseDtoFromJSON(
  json: any
): OpportunitySummaryResponseDto {
  return OpportunitySummaryResponseDtoFromJSONTyped(json, false);
}

export function OpportunitySummaryResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OpportunitySummaryResponseDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: json["title"],
    contactName: json["contactName"],
    requiredPeopleCount: json["requiredPeopleCount"],
    startTime: json["startTime"],
    endTime: json["endTime"],
    opportunityId: json["opportunityId"],
    postedTime: json["postedTime"],
  };
}

export function OpportunitySummaryResponseDtoToJSON(
  value?: OpportunitySummaryResponseDto | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    contactName: value.contactName,
    requiredPeopleCount: value.requiredPeopleCount,
    startTime: value.startTime,
    endTime: value.endTime,
    opportunityId: value.opportunityId,
    postedTime: value.postedTime,
  };
}
