/* tslint:disable */
/* eslint-disable */
/**
 * Volunteer Victoria - Community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ThreadStartDto
 */
export interface ThreadStartDto {
  /**
   *
   * @type {string}
   * @memberof ThreadStartDto
   */
  applicantName: string;
  /**
   *
   * @type {string}
   * @memberof ThreadStartDto
   */
  message: string;
}

/**
 * Check if a given object implements the ThreadStartDto interface.
 */
export function instanceOfThreadStartDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "applicantName" in value;
  isInstance = isInstance && "message" in value;

  return isInstance;
}

export function ThreadStartDtoFromJSON(json: any): ThreadStartDto {
  return ThreadStartDtoFromJSONTyped(json, false);
}

export function ThreadStartDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ThreadStartDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    applicantName: json["applicantName"],
    message: json["message"],
  };
}

export function ThreadStartDtoToJSON(value?: ThreadStartDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    applicantName: value.applicantName,
    message: value.message,
  };
}
