openapi: 3.0.3
info:
  title: Volunteer Victoria - Community
  version: "1.0"
paths:
  /opportunity:
    get:
      responses:
        '200':
          description: Summary of opportunities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OpportunitySummary"
                  
    post:
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Opportunity"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Opportunity"
        
    
  /opportunity/{opportunityId}:
    get:
      parameters:
      - name: opportunityId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description:  Opportunity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Opportunity"
  
components:
  schemas:
    OpportunitySummary:
      type: object
      properties:
        opportunityId:
          type: string
        title:
          type: string
        contactDetails:
          type: object
          properties:
            name: 
              type: string
        volunteerRequirements:
          type: object
          properties:
            peopleCount: 
              type: number
        startTime:
          type: number
          example: 1666817899
        endTime:
          type: number
          example: 1666817900
     
    Opportunity:
      type: object
      allOf:
      - $ref: "#/components/schemas/OpportunitySummary"
      - properties:
          description:
            type: string
          location:
            type: object
            properties:
              name: 
                type: string
              type:
                type: string
                enum: [indoors, outdoors]
          contactDetails:
            type: object
            properties:
              name: 
                type: string
              email:
                type: string
                format: email
              phoneNumber:
                type: string
          volunteerRequirements:
            type: object
            properties:
              criminalRecordCheckRequired:
                type: boolean
       
    UserSummary:
      type: object
      properties:
        displayName:
          type: string
        userId:
          type: string
     
    Error:
      type: object
      properties:
        message:
          type: string
