name: Deploy (Infrastructure + Backend)
on:
  push:
    branches:
      - dev
      - test
      - prod
    paths:
      - "packages/backend/**"
      - "terraform/**"
  workflow_dispatch:

env:
  TF_VERSION: 1.4.2

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Extract branch name
        run: |
          echo "${GITHUB_REF#refs/heads/}"
          echo "ENV_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn

      - name: Build backend
        run: make backend-build

      - uses: hashicorp/setup-terraform@v2
        name: Set-up terraform
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIARPNKKEIOBRA6KVOH
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Init terraform
        run: make tf-init

      - name: Deploy infra and backend
        run: make tf-apply
