name: Deploy Backend Changes
on:
  push:
    branches:
      - dev
    paths:
      - "packages/backend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn

      - name: Build backend
        run: make backend-build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIARPNKKEIOBRA6KVOH
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Deploy backend
        run: make backend-deploy
